### ISSUE TITLE
BACKUP_PATHS documentation

### ISSUE THREAD

**Issue by M-M-M-M** [mrichtarsky/glacier_deep_archive_backup#2]
Are the backup paths relative to the ZFS pool? if yes, documentation could be more detailed.

For instance, with a ZFS pool name myzpool/BACKUP/app1 mounted on /myzpool/BACKUP/app1

The backup paths

BACKUP_PATHS=(
    "file1.txt"
    "pics"
    "sports/nba"
)

is for  /myzpool/BACKUP/app1/file1.txt,  /myzpool/BACKUP/app1/pics, and  /myzpool/BACKUP/app1/sports/nba

How to backup everything in the ZFS pool? Could we use wildcard such as "*"?

**Comment by mrichtarsky** [comment]
> Are the backup paths relative to the ZFS pool? if yes, documentation could be more detailed.

Fixed

> How to backup everything in the ZFS pool? Could we use wildcard such as "*"?

That's a good point. I think supporting wildcard expansion via https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob would be a good idea.
